site_name: Projeto Microserviços - Julia Almeida Silva
site_description: Documentação do projeto de microserviços desenvolvido durante a disciplina
site_author: Julia Almeida Silva
site_url: https://juliaas2.github.io/site

# Repository
repo_name: juliaas2/site
repo_url: https://github.com/juliaas2/site
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

# Plugins
plugins:
  - search:
      lang: pt
  - mermaid2:
      arguments:
        theme: |
          ^(auto|dark|light)$

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - abbr

# Navigation
nav:
  - Home: index.md
  - Sobre: sobre.md
  - Atividades:
    - Atividade 1 - Exchange API: atividades/atividade1.md
    - Atividade 2 - Product API: atividades/atividade2.md
    - Atividade 3 - Order Service: atividades/atividade3.md
    - Atividade 4 - Jenkins Pipeline: atividades/atividade4.md
    - Atividade 5 - Kubernetes: atividades/atividade5.md
  - Projeto Final:
    - Documentação: projeto/documentacao.md
    - Apresentação: projeto/apresentacao.md
    - Vídeo: projeto/video.md
  - Referências:
    - Repositórios: repositorios.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/juliaas2
      name: GitHub
  generator: false

# Copyright
copyright: Copyright &copy; 2025 Julia Almeida Silva